### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Perflyst** [SapuSeven/BetterUntis#1]
Nice to see a new BetterUntis written in Kotlin.

Since this new version does not contain any closed source libs you can publish it on F-Droid. I would really like to see it there.

**Comment by SapuSeven** [comment]
Thanks for the positive feedback.
I chose to stay "all open source" with F-Droid in mind, but I don't know if I'm ready to publish it yet. I think I will try to include as many features as possible from the previous version before I publish BetterUntis to F-Droid.

**Comment by Perflyst** [comment]
Just to make this complete, my current fork of the legacy version (OpenUntis) will be archived if yours is published.

**Comment by Perflyst** [comment]
As far as I see all features from the previous version are included now?

**Comment by SapuSeven** [comment]
Yes, I am almost ready to publish. I just want to get the [Info Center](https://github.com/SapuSeven/BetterUntis/tree/info-center) finished, then I'll upload it to F-Droid.

**Comment by Perflyst** [comment]
Ok, so I created the yml file which needs to be submitted to F-Droid.

While testing the build I got an error `app/build.gradle': 36: unexpected token: } @ line 36, column 3.`
I do not find the wrong } in the gradle file, do you see it?

Also feel free to edit the description of the app.

<details>
<summary>metadata/com.sapuseven.untis.yml</summary>

```
AntiFeatures:
  - NonFreeNet
Categories:
  - Internet
License: GPL-3.0-or-later
SourceCode: https://github.com/SapuSeven/BetterUntis
IssueTracker: https://github.com/SapuSeven/BetterUntis/issues
Changelog: https://github.com/SapuSeven/BetterUntis/releases

AutoName: BetterUntis
Description: |-
    An alternative FLOSS Android client for the Untis timetable system.

    Untis is a proprietary timetable software. More information about Untis can be
    found at https://untis.at. To use Untis, your school must provide it. Your
    school must also give you an account with which you can access your current
    timetable. Why use this app when there is an official one? The official app is
    also proprietary and includes libraries from google and other tracking software.
    BetterUntis offers you exactly the same features and even more. Free choice of
    themes and dark mode are of course also included.

    WebUntis is a non-free network.

RepoType: git
Repo: https://github.com/SapuSeven/BetterUntis

Builds:
  - versionName: 3.0.2
    versionCode: 13
    commit: 429fe49b8dd7ff084e2885a34bb2b286d74da922
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version v%v
UpdateCheckMode: Tags
CurrentVersion: 3.0.2
CurrentVersionCode: 13
```
</details>
